// Copy the costing engine out of the web app (../index.html) into an ES module the Worker
// imports. The engine lives between the ENGINE-START / ENGINE-END markers in index.html and
// is pure (no DOM), so the connector prices a quote with exactly the code the app runs.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const appHtml = readFileSync(join(here, '..', '..', 'index.html'), 'utf8');
const START = '/* ===== ENGINE-START ===== */';
const END = '/* ===== ENGINE-END ===== */';
const a = appHtml.indexOf(START), b = appHtml.indexOf(END);
if (a < 0 || b < 0 || b < a) {
  console.error('extract-engine: ENGINE-START / ENGINE-END markers not found in index.html');
  process.exit(1);
}
const body = appHtml.slice(a + START.length, b);
const out = `// GENERATED by scripts/extract-engine.mjs from ../index.html. Do not edit; edit the app.
${body}
export { PROC_COLS, defaultProcessRates, defaultMaterials, num, roundUpTo10, computePartWith };
`;
writeFileSync(join(here, '..', 'src', 'engine.generated.js'), out);
console.log('extract-engine: wrote src/engine.generated.js');
